**2. zadatak - Sustavi linearnih jednadžbi i uvjetovanost (LV2)**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numpy import sign
from scipy.linalg import lu, lu_factor, lu_solve


In [ ]:
# Definicija matrice A i vektora b
A = np.array([[3,-0.1,-0.2], [0.1,7,-0.3],[0.3,-0.2,10]])
b = np.array([7.85,-19.3,71.4])

Stvarna rješenja su x1=3, x2=-2.5, x3=7

1. Riješite sustav:

• Gaussovom eliminacijom s parcijalnim pivotiranjem,

• LU dekompozicijom.


Gauss

In [ ]:
def gauss_solve(A, b):
    A = A.astype(float).copy()
    b = b.astype(float).copy()
    n = len(b)

    # 1) Forward eliminacija s djelomičnim pivotiranjem
    for k in range(n-1):
        # odaberi pivot red (najveći po apsolutnoj vrijednosti u stupcu k)
        pivot = k + np.argmax(np.abs(A[k:, k]))
        if A[pivot, k] == 0:
            raise ValueError("Matrica je singularna ili blizu singularne.")
        # zamijeni redove u A i b ako treba
        if pivot != k:
            A[[k, pivot]] = A[[pivot, k]]
            b[[k, pivot]] = b[[pivot, k]]

        # eliminiraj ispod pivota
        for i in range(k+1, n):
            lam = A[i, k] / A[k, k]
            A[i, k:] = A[i, k:] - lam * A[k, k:]
            b[i] = b[i] - lam * b[k]

    # 2) Povratna (unatrag) supstitucija
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        s = np.dot(A[i, i+1:], x[i+1:])
        x[i] = (b[i] - s) / A[i, i]
    return x

x_gauss = gauss_solve(A, b)
print("\nRješenje sustava:")
print("x1 =", x_gauss[0])
print("x2 =", x_gauss[1])
print("x3 =", x_gauss[2])


Rješenje sustava:
x1 = 3.0
x2 = -2.5
x3 = 7.000000000000002


LU

In [ ]:
# Izračun LU dekompozicije sa permutacijom
P, L, U = lu(A)

print("Matrica P (permutacijska):")
print(P)
print("\nMatrica L (donje trokutasta):")
print(L)
print("\nMatrica U (gornje trokutasta):")
print(U)

# Brzo rješenje koristeći LU faktoriranje
lu_and_piv = lu_factor(A)
#x = lu_solve(lu_and_piv, b)
x_LU=np.linalg.solve(A, b)
print("\nRješenje sustava:")
print("x1 =", x_LU[0])
print("x2 =", x_LU[1])
print("x3 =", x_LU[2])


Matrica P (permutacijska):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrica L (donje trokutasta):
[[ 1.          0.          0.        ]
 [ 0.03333333  1.          0.        ]
 [ 0.1        -0.02712994  1.        ]]

Matrica U (gornje trokutasta):
[[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]]

Rješenje sustava:
x1 = 3.0
x2 = -2.5
x3 = 7.000000000000002


2. Izračunajte rezidual rješenja.


In [ ]:
x_true = np.array([3,-2.5,7])
e_gauss = x_gauss - x_true
r_gauss = b - A @ x_gauss
norm_e_gauss = np.linalg.norm(e_gauss, np.inf)
norm_r_gauss = np.linalg.norm(r_gauss, np.inf)
norm_x_true = np.linalg.norm(x_true, np.inf)
norm_b = np.linalg.norm(b, np.inf)

e_LU = x_LU - x_true
r_LU = b - A @ x_LU
norm_e_LU = np.linalg.norm(e_LU, np.inf)
norm_r_LU = np.linalg.norm(r_LU, np.inf)
print("Gauss")
print("Numericko rjesenje:", x_gauss)
print("||e||_inf =", norm_e_gauss)
print("||r||_inf =", norm_r_gauss)

print("LU")
print("Numericko rjesenje:", x_LU)
print("||e||_inf =", norm_e_LU)
print("||r||_inf =", norm_r_LU)


Gauss
Numericko rjesenje: [ 3.  -2.5  7. ]
||e||_inf = 1.7763568394002505e-15
||r||_inf = 1.4210854715202004e-14
LU
Numericko rjesenje: [ 3.  -2.5  7. ]
||e||_inf = 1.7763568394002505e-15
||r||_inf = 1.4210854715202004e-14


In [ ]:
x_true = np.array([3,-2.5,7])


Numericko rjesenje: [ 3.  -2.5  7. ]
||e||_inf = 1.7763568394002505e-15
||r||_inf = 1.4210854715202004e-14


3. Procijenite broj uvjetovanosti matrice sustava.


In [ ]:
kappa = np.linalg.cond(A, np.inf)
print("Broj uvjetovanosti :", kappa)


Broj uvjetovanosti : 3.6144243248254124


**Broj uvjetovanosti je ok, inače težimo 1**

4. Komentirajte pouzdanost dobivenog rješenja.

Obje metode imaju istu pogrešku i rezidual, zato što obje daju doslovno isto rješenje.

x1 i x2 su točno onakvi kakvi trebaju biti dok x3 ima zanemarivo odstupanje